module.exports._data = [
  {
    name: "Hopkins Ave",
    city: "New York",
    price: 1500,
    moveIn: "September",
    address: "13 Hopkins Ave, Manhattan, NY",
    bed: 2,
    bath: 2,
    type: "House",
    img: "",
  },
  {
    name: "Baldwin Ave",
    city: "New York",
    price: 1200,
    moveIn: "September",
    address: "11 Baldwin Ave, Queens, NY",
    bed: 2,
    bath: 1,
    type: "House",
    img: "",
  },
  {
    name: "JFK Avenue",
    city: "New York",
    price: 1000,
    moveIn: "October",
    address: "30 JFK Avenue, Brooklyn, NY",
    bed: 2,
    bath: 1,
    type: "Apartment",
    img: "",
  },
  {
    name: "SouthHampton",
    city: "New York",
    price: 2000,
    moveIn: "September",
    address: "25 River Drive, Manhattan, NY",
    bed: 3,
    bath: 2,
    type: "Apartment",
    img: "",
  },
  {
    name: "Riverside",
    city: "New York",
    price: 3200,
    moveIn: "August",
    address: "30 River Drive, Manhattan, NY",
    bed: 2,
    bath: 2,
    type: "Apartment",
    img: "",
  },
  {
    name: "Palisade Ave",
    city: "Boston",
    price: 1500,
    moveIn: "October",
    address: "10 Palisade Ave, Boston, MA",
    bed: 2,
    bath: 1,
    type: "House",
    img: "",
  },
  {
    name: "Pine Street",
    city: "Boston",
    price: 1200,
    moveIn: "September",
    address: "88 Pine Street, Boston, MA",
    bed: 2,
    bath: 1,
    type: "House",
    img: "",
  },
  {
    name: "Maple Street",
    city: "Boston",
    price: 2000,
    moveIn: "September",
    address: "90 Maple Street, Boston, MA",
    bed: 3,
    bath: 2,
    type: "House",
    img: "",
  },
  {
    name: "Cedar Street",
    city: "Boston",
    price: 1500,
    moveIn: "October",
    address: "5 Cedar Street, Boston, MA",
    bed: 2,
    bath: 1,
    type: "Apartment",
    img: "",
  },
  {
    name: "Oak Street",
    city: "Boston",
    price: 2500,
    moveIn: "August",
    address: "2 Oak Street, Boston, MA",
    bed: 3,
    bath: 2,
    type: "Apartment",
    img: "",
  },
  {
    name: "Elm Street",
    city: "Philadelphia",
    price: 1200,
    moveIn: "August",
    address: "13 Elm Street, Philadelphia, PA",
    bed: 2,
    bath: 1,
    type: "House",
    img: "",
  },
  {
    name: "Lakeview",
    city: "Philadelphia",
    price: 1500,
    moveIn: "August",
    address: "10 Lakeview, Philadelphia, PA",
    bed: 2,
    bath: 1,
    type: "House",
    img: "",
  },
  {
    name: "Hill Ave",
    city: "Philadelphia",
    price: 2000,
    moveIn: "September",
    address: "90 Hill Ave, Philadelphia, PA",
    bed: 3,
    bath: 2,
    type: "Apartment",
    img: "",
  },
  {
    name: "Ninth Street",
    city: "Philadelphia",
    price: 2700,
    moveIn: "September",
    address: "14 Ninth Street, Philadelphia, PA",
    bed: 3,
    bath: 2,
    type: "Apartment",
    img: "",
  },
  {
    name: "Washington Ave",
    city: "Philadelphia",
    price: 2200,
    moveIn: "October",
    address: "45 Washington Ave, Philadelphia, PA",
    bed: 3,
    bath: 2,
    type: "Apartment",
    img: "",
  },
];
